#!/usr/bin/env python3
"""
Real-time EMG Data Visualizer for Interval Collection
Reads from CSV file generated by interval C++ collector and displays live graphs
Shows labels (clench/rest) and highlights collection periods
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from collections import deque
import numpy as np
import time
import os

# Colors for each channel
channel_colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', 
                  '#9467bd', '#8c564b', '#e377c2', '#7f7f7f']

# Colors for labels
label_colors = {
    'clench': '#ff4444',  # Red for clench
    'rest': '#44ff44'     # Green for rest
}

class IntervalEMGVisualizer:
    def __init__(self, csv_filename, window_size=1000):
        self.csv_filename = csv_filename
        self.window_size = window_size  # Keep last 1000 samples (5 seconds at 200Hz)
        
        # Initialize data buffers for 8 channels
        self.channel_data = [deque(maxlen=window_size) for _ in range(8)]
        self.timestamps = deque(maxlen=window_size)
        self.labels = deque(maxlen=window_size)
        self.last_row = 0
        self.sample_count = 0
        self.current_label = None
        
        # Set up matplotlib figure with subplots
        self.fig = plt.figure(figsize=(14, 10))
        
        # Main plot for EMG data
        self.ax = self.fig.add_subplot(2, 1, 1)
        self.ax.set_xlabel('Time (ms)', fontsize=10)
        self.ax.set_ylabel('EMG Value', fontsize=10)
        self.ax.set_ylim(-100, 100)
        self.ax.grid(True, alpha=0.3)
        self.ax.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
        
        # Create lines for each channel
        self.lines = []
        for channel in range(8):
            line, = self.ax.plot([], [], color=channel_colors[channel], 
                               label=f'Channel {channel+1}', linewidth=1.5)
            self.lines.append(line)
        
        # Add legend
        self.ax.legend(loc='upper right', ncol=2, fontsize=9)
        
        # Label indicator plot
        self.ax_label = self.fig.add_subplot(2, 1, 2)
        self.ax_label.set_xlabel('Time (ms)', fontsize=10)
        self.ax_label.set_ylabel('Label', fontsize=10)
        self.ax_label.set_ylim(-0.5, 1.5)
        self.ax_label.set_yticks([0, 1])
        self.ax_label.set_yticklabels(['REST', 'CLENCH'])
        self.ax_label.grid(True, alpha=0.3)
        
        # Create line for label visualization
        self.label_line, = self.ax_label.plot([], [], linewidth=3, alpha=0.7)
        
        # Store label regions for background shading
        self.label_regions = []
        
        plt.tight_layout()
    
    def update_data(self):
        """Read new data from CSV file"""
        if not os.path.exists(self.csv_filename):
            return
        
        try:
            # Read only new rows
            df = pd.read_csv(self.csv_filename, skiprows=range(1, self.last_row + 1))
            
            if len(df) == 0:
                return
            
            # Update last row counter
            self.last_row += len(df)
            
            # Add new data to buffers
            for _, row in df.iterrows():
                # Convert timestamp to milliseconds
                timestamp_ms = row['timestamp'] * 1000
                self.timestamps.append(timestamp_ms)
                
                # Get label
                label = row.get('label', 'unknown')
                self.labels.append(label)
                if label != 'unknown':
                    self.current_label = label
                
                # Add data for each channel
                for channel in range(8):
                    self.channel_data[channel].append(row[f'emg{channel+1}'])
                
                self.sample_count += 1
            
            # Update label regions for background shading
            self.update_label_regions()
        
        except Exception as e:
            print(f"Error reading CSV: {e}")
    
    def update_label_regions(self):
        """Update background regions based on labels"""
        if len(self.timestamps) == 0:
            return
        
        # Clear existing regions
        for patch in self.label_regions:
            patch.remove()
        self.label_regions.clear()
        
        # Find label transitions
        time_array = np.array(self.timestamps)
        label_array = np.array(self.labels)
        
        if len(time_array) < 2:
            return
        
        # Find where labels change
        label_changes = []
        current_label = label_array[0]
        for i in range(1, len(label_array)):
            if label_array[i] != current_label:
                label_changes.append((i, current_label, label_array[i]))
                current_label = label_array[i]
        
        # Add regions for each label segment
        start_idx = 0
        for change_idx, old_label, new_label in label_changes:
            if start_idx < change_idx:
                start_time = time_array[start_idx]
                end_time = time_array[change_idx - 1]
                color = label_colors.get(old_label, 'gray')
                alpha = 0.15 if old_label == 'rest' else 0.2
                
                rect = plt.Rectangle((start_time, -100), end_time - start_time, 200,
                                   facecolor=color, alpha=alpha, zorder=0)
                self.ax.add_patch(rect)
                self.label_regions.append(rect)
            
            start_idx = change_idx
        
        # Add final region
        if start_idx < len(time_array):
            start_time = time_array[start_idx]
            end_time = time_array[-1]
            final_label = label_array[-1]
            color = label_colors.get(final_label, 'gray')
            alpha = 0.15 if final_label == 'rest' else 0.2
            
            rect = plt.Rectangle((start_time, -100), end_time - start_time, 200,
                               facecolor=color, alpha=alpha, zorder=0)
            self.ax.add_patch(rect)
            self.label_regions.append(rect)
    
    def animate(self, frame):
        """Animation function called by FuncAnimation"""
        self.update_data()
        
        if len(self.timestamps) == 0:
            return self.lines + [self.label_line]
        
        # Convert timestamps to numpy array
        time_array = np.array(self.timestamps)
        
        # Update each channel line
        for channel in range(8):
            if len(self.channel_data[channel]) > 0:
                channel_values = np.array(self.channel_data[channel])
                self.lines[channel].set_data(time_array, channel_values)
        
        # Update label visualization
        if len(self.labels) > 0:
            label_array = np.array(self.labels)
            # Convert labels to numeric: rest=0, clench=1
            label_numeric = np.array([1 if label == 'clench' else 0 for label in label_array])
            self.label_line.set_data(time_array, label_numeric)
            
            # Set color based on current label
            if self.current_label:
                self.label_line.set_color(label_colors.get(self.current_label, 'gray'))
        
        # Scrolling window - show last 5 seconds (5000ms)
        if len(time_array) > 0:
            current_time = time_array[-1]
            window_duration = 5000  # 5 seconds in milliseconds
            x_min = max(0, current_time - window_duration)
            x_max = current_time + 200
            
            self.ax.set_xlim(x_min, x_max)
            self.ax_label.set_xlim(x_min, x_max)
        
        # Update title with sample count and current label
        label_text = f"Current: {self.current_label.upper()}" if self.current_label else "No label"
        self.ax.set_title(f'EMG Data - 8 Channels (Samples: {self.sample_count}, {label_text})', 
                         fontsize=12, fontweight='bold')
        
        return self.lines + [self.label_line]
    
    def run(self):
        """Start the animation"""
        ani = animation.FuncAnimation(
            self.fig, 
            self.animate, 
            interval=50,  # Update every 50ms
            blit=False,
            cache_frame_data=False
        )
        
        try:
            plt.show()
        except KeyboardInterrupt:
            print("\n\nInterrupted by user. Stopping...")
        finally:
            print(f"\nVisualization stopped. Total samples displayed: {self.sample_count}")

if __name__ == "__main__":
    import sys
    import glob
    
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    else:
        # Find the most recent interval EMG CSV file
        csv_files = glob.glob("emg_data_interval_*.csv")
        if csv_files:
            csv_file = max(csv_files, key=os.path.getctime)
            print(f"Using most recent file: {csv_file}")
        else:
            print("No CSV file specified and no emg_data_interval_*.csv files found.")
            print("Usage: python emg_visualizer_interval.py <csv_filename>")
            sys.exit(1)
    
    print(f"CSV file: {csv_file}")
    print("Close the plot window or press Ctrl+C to stop visualization...")
    print("=" * 60)
    print("Legend:")
    print("  - Red background: CLENCH periods")
    print("  - Green background: REST periods")
    print("  - Bottom plot shows label timeline")
    print("=" * 60)
    
    visualizer = IntervalEMGVisualizer(csv_file)
    visualizer.run()

